name: CD — clients-service to GHCR

on:
  push:
    branches: [ "main" ]   # publica en main
    tags:     [ "v*" ]     # y en tags tipo v1.0.0

jobs:
  docker-publish:
    name: Build & Push Docker (GHCR)
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write   # necesario para publicar en GHCR
    defaults:
      run:
        working-directory: services/clients-service

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/clients-service
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=sha
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build & Push
        uses: docker/build-push-action@v6
        with:
          context: ./services/clients-service
          file: ./services/clients-service/Dockerfile
          push: true
          platforms: linux/amd64
          provenance: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Output image tags
        run: echo "${{ steps.meta.outputs.tags }}"
